name = "dog-personality-quiz"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[env.production]
name = "dog-personality-quiz"

[[d1_databases]]
binding = "DB"
database_name = "dog-quiz-db"
database_id = "35b841f6-86ca-48e0-9754-921b1336890e"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "dog-quiz-images"

[ai]
binding = "AI"

[vars]
ENVIRONMENT = "development"
